# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArtnetToHue < Formula
  desc "artnet-to-hue is a bridge between Art-Net and Philips Hue."
  homepage "https://github.com/techwolf12/artnet-to-hue"
  version "0.1.0"
  license "MIT"

  on_macos do
    url "https://github.com/Techwolf12/artnet-to-hue/releases/download/v0.1.0/artnet-to-hue_Darwin_all.tar.gz"
    sha256 "6f9abaede09ceb394b5da723833a2dcf8549f812206513b757ca59dc14ff0d6a"

    def install
      bin.install "artnet-to-hue"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Techwolf12/artnet-to-hue/releases/download/v0.1.0/artnet-to-hue_Linux_x86_64.tar.gz"
      sha256 "709069b7e3fcdb05c7bf59112b72a8cd6669b08ef180f7b2d438786eaed9a6e2"
      def install
        bin.install "artnet-to-hue"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Techwolf12/artnet-to-hue/releases/download/v0.1.0/artnet-to-hue_Linux_arm64.tar.gz"
      sha256 "2cdb74a052033cf5839d23e406462690fb5efb1eb4d55239ddca35e7d4da6725"
      def install
        bin.install "artnet-to-hue"
      end
    end
  end
end
