# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qrkey < Formula
  desc "qrkey is a command-line tool for generating and recovering QR codes from files for offline private key backup."
  homepage "https://github.com/techwolf12/qrkey"
  version "0.0.1"
  license "MIT"

  on_macos do
    url "https://github.com/Techwolf12/qrkey/releases/download/v0.0.1/qrkey_Darwin_all.tar.gz"
    sha256 "e479f307021f72a4def80a39edfe478e8775d97c55c63b023a3baa52bd6c221f"

    def install
      bin.install "qrkey"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Techwolf12/qrkey/releases/download/v0.0.1/qrkey_Linux_x86_64.tar.gz"
      sha256 "742f010a9026e4448f943eee723de220a1dd64a82d31ef5da358a21873af7b3d"
      def install
        bin.install "qrkey"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Techwolf12/qrkey/releases/download/v0.0.1/qrkey_Linux_arm64.tar.gz"
      sha256 "6556f59ad408b10cbd2996e95f6648edf28968f764c3345e8914ae2e7017845d"
      def install
        bin.install "qrkey"
      end
    end
  end
end
